name: Deploy to PROD

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy PROD
        shell: cmd
        run: >
          "C:\Program Files\CODESYS 3.5.21.40\CODESYS\Common\CODESYS.exe"
          --noUI
          --profile="CODESYS V3.5 SP21 Patch 4"
          --runscript="C:\PLC_REPO\scripts\deploy_prod.py"
          --scriptargs:"C:\Users\Test_bench\Documents\PLC_PROD.project"